spring.application.name=springboot-app-devops

spring.datasource.url=jdbc:mysql://localhost:3306/usuarios_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

sonar.projectKey=jos-rojo17_Prueba_parcial2
sonar.organization=jos-rojo17

sonar.host.url=https://sonarcloud.io

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml