name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar proyecto
        run: mvn clean verify

      - name: Analisis SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=jos-rojo17_Prueba_parcial2 \
            -Dsonar.organization=jos-rojo17 \
            -Dsonar.host.url=https://snarcloud.io \
            -Dsonar.login=${{ secrets.SNAR_TOKEN }}

      - name: Construir Docker
        run: docker build -t app-devops .

      - name: Levantar contenedores
        run: docker compose up -d